import type { Metadata } from "next";
import { Poppins, Roboto } from "next/font/google";

import "swiper/css";
import "swiper/css/pagination";

import "./custom.css";
import "./globals.css";

import Footer from "@/Components/layouts/Footer";
import Header from "@/Components/layouts/Header";
import { AuthProvider } from "@/hook/useAuth";
import ReactQueryProvider from "@/hook/ReactQueryProvider";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      data-scroll-behavior="smooth"
      className={`${poppins.variable} ${roboto.variable} h-full antialiased`}
    >
      <body
        suppressHydrationWarning
        className="min-h-full flex flex-col"
      >
        <ReactQueryProvider>
          <AuthProvider>
    
            <Header />
            <main className="flex-1">
              {children}
            </main>
            <Footer />
          </AuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}